package ir.map.sdksample;

import android.app.Application;

import ir.map.navigationsdk.MapirNavigation;

public class AppController extends Application {
    @Override
    public void onCreate() {
        super.onCreate();

        //TODO Please add your API_KEY
        MapirNavigation.init(this, "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjNkNDRkODBmMzMxMDQ2NDM2NGQ3NWFiZDdlMDkyOTRjNWFiNzFkMTZlN2U3YTE1MGE1YzljNmFmY2Q2OTkyZTk4NmJiMzZjNzA1MTAyYzg1In0.eyJhdWQiOiI5NDQ5IiwianRpIjoiM2Q0NGQ4MGYzMzEwNDY0MzY0ZDc1YWJkN2UwOTI5NGM1YWI3MWQxNmU3ZTdhMTUwYTVjOWM2YWZjZDY5OTJlOTg2YmIzNmM3MDUxMDJjODUiLCJpYXQiOjE1OTA5MjQyMzQsIm5iZiI6MTU5MDkyNDIzNCwiZXhwIjoxNTkzNjAyNjM0LCJzdWIiOiIiLCJzY29wZXMiOlsiYmFzaWMiXX0.j7Q2RDQTucHDtGaMddk3vA8e0Nb9Hfg8pI1JlZNaEZ6FK2IZIxtGGP_rKFrF6mlIZ0NPqXSL54xPEmJyuBFet9tsD-aMvlumSahJMRvwOV8eeDi5tlWiMZof3vc1vQt6bc7AGVSLNSomMmIC0T59Np0-FeXSztpPHxzAJuiUihGKgCKFvDg6VUPqo7nWlezY5cfYZBegZoJ3vU9ReluMptTC-0bEjB4ltq-4O0kUU2EwicFLiWpX7ozSlLNBf8GDPry4SvoGGRQQ5pV5LLLKF_Ye2tUkRTyFRR2gBar9IMZVgBfaeVwCVYy_blKx6OJ0gNDg__ahNgOKvAJavUvA1Q");
    }
}